/* DO NOT EDIT */
/* This file was generated by Stone */

package autosaveworld.zlibs.com.dropbox.core.v2;

import autosaveworld.zlibs.com.dropbox.core.v2.files.DbxUserFilesRequests;

/**
 * Base class for user auth clients.
 */
public class DbxClientV2Base {
    protected final DbxRawClientV2 _client;

    private final DbxUserFilesRequests files;

    /**
     * For internal use only.
     *
     * @param _client  Raw v2 client to use for issuing requests
     */
    protected DbxClientV2Base(DbxRawClientV2 _client) {
        this._client = _client;
        this.files = new DbxUserFilesRequests(_client);
    }

    /**
     * Returns client for issuing requests in the {@code "files"} namespace.
     *
     * @return Dropbox files client
     */
    public DbxUserFilesRequests files() {
        return files;
    }

}
