/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * This namespace contains endpoints and data types for basic file operations.
 *
 * <p> See {@link autosaveworld.zlibs.com.dropbox.core.v2.files.DbxUserFilesRequests} for a list of
 * possible requests for this namespace. </p>
 */
package autosaveworld.zlibs.com.dropbox.core.v2.files;

