/* DO NOT EDIT */
/* This file was generated by Stone */

package autosaveworld.zlibs.com.dropbox.core.v2.team;

import autosaveworld.zlibs.com.dropbox.core.DbxApiException;
import autosaveworld.zlibs.com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link GroupMembersAddError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#groupsMembersAdd(GroupSelector,java.util.List,boolean)}.
 * </p>
 */
public class GroupMembersAddErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/groups/members/add

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#groupsMembersAdd(GroupSelector,java.util.List,boolean)}.
     */
    public final GroupMembersAddError errorValue;

    public GroupMembersAddErrorException(String routeName, String requestId, LocalizedText userMessage, GroupMembersAddError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
