/* DO NOT EDIT */
/* This file was generated by Stone */

package autosaveworld.zlibs.com.dropbox.core.v2.team;

import autosaveworld.zlibs.com.dropbox.core.DbxApiException;
import autosaveworld.zlibs.com.dropbox.core.LocalizedText;

/**
 * Exception thrown when the server responds with a {@link MembersRecoverError}
 * error.
 *
 * <p> This exception is raised by {@link
 * DbxTeamTeamRequests#membersRecover(UserSelectorArg)}. </p>
 */
public class MembersRecoverErrorException extends DbxApiException {
    // exception for routes:
    //     2/team/members/recover

    private static final long serialVersionUID = 0L;

    /**
     * The error reported by {@link
     * DbxTeamTeamRequests#membersRecover(UserSelectorArg)}.
     */
    public final MembersRecoverError errorValue;

    public MembersRecoverErrorException(String routeName, String requestId, LocalizedText userMessage, MembersRecoverError errorValue) {
        super(requestId, userMessage, buildMessage(routeName, userMessage, errorValue));
        if (errorValue == null) {
            throw new NullPointerException("errorValue");
        }
        this.errorValue = errorValue;
    }
}
