/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * See {@link autosaveworld.zlibs.com.dropbox.core.v2.team.DbxTeamTeamRequests} for a list of
 * possible requests for this namespace.
 */
package autosaveworld.zlibs.com.dropbox.core.v2.team;

