/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * This namespace contains helper entities for property and property/template
 * endpoints.
 */
package autosaveworld.zlibs.com.dropbox.core.v2.properties;

