/* DO NOT EDIT */
/* This file was generated by Stone */

/**
 * This namespace contains endpoints and data types for creating and managing
 * shared links and shared folders.
 *
 * <p> See {@link autosaveworld.zlibs.com.dropbox.core.v2.sharing.DbxUserSharingRequests} for a list
 * of possible requests for this namespace. </p>
 */
package autosaveworld.zlibs.com.dropbox.core.v2.sharing;

