broadcast:
  pre: '&9AutoSaving'
  post: '&9AutoSave Complete'
broadcastbackup:
  pre: '&9AutoBackuping'
  post: '&9AutoBackup Complete'
broadcastpurge:
  pre: '&9AutoPurging'
  post: '&9AutoPurge Complete'
autorestart:
  restarting: '&9Server is restarting'
  countdown: '&9Server will restart in {SECONDS} seconds'
worldregen:
  kickmessage: '&9Server is regenerating map, please come back later'
insufficentpermissions: '&cYou do not have access to that command.'
